name: chassealerte
description: Application mobile pour la gestion des battues
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^8.0.0
  flutter_map: ^6.1.0
  font_awesome_flutter: ^10.5.0
  geolocator: ^10.1.0
  geocoding: ^2.1.0
  latlong2: ^0.9.0
  apple_maps_flutter: ^1.4.0
  provider: ^6.0.0
  flutter_secure_storage: ^9.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.2
  flutter_map_cancellable_tile_provider: ^2.0.0
  flutter_dotenv: ^5.2.1
  google_maps_flutter: ^2.6.0
  google_maps_flutter_web: ^0.5.0
  socket_io_client: ^2.0.3+1
  http: ^1.2.2
  intl: ^0.19.0
  flutter_typeahead: ^5.2.0
  dio: ^5.9.0
  fl_chart: ^0.66.2
  connectivity_plus: ^6.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  hive_generator: ^2.0.0
  build_runner: ^2.4.0
flutter:
  uses-material-design: true   # â† OBLIGATOIRE pour flutter_typeahead

  assets:
   - assets/image/
   - assets/.env
   - assets/icons/weather/
   - assets/icons/




